apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller
  namespace: kubewarden
spec:
  endpoints:
    - interval: 10s 
      port: metrics
  namespaceSelector:
    matchNames:
      - kubewarden
  selector:
    matchLabels:
      app.kubernetes.io/name: kubewarden-controller
